---
#Copyright 2016 Kumar Jadav
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.


- name: Check the file status
  gather_facts: no
  become: true
  hosts: localhost

  vars_files: 
  - common-tasks/libvirt-vars.yml

  tasks:

  - include: common-tasks/libvirt-facts.yml

  - name: Copy and create a RHEL master node.
    synchronize: 
      src: "{{ rhel_image }}"
      dest: "{{ master }}"
    become: True

  - name: Copy and create a RHEL slave node.
    synchronize: 
      src: "{{ rhel_image }}"
      dest: "{{ slave }}"
    become: True

